#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: web-app
#spec:
#  rules:
#    - host: "webb-app.com"
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: web-app
#                port:
#                  number: 80
