apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./kubernetes/cluster/marco-f-cluster-dev/web-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: web-app
  timeout: 5m
  force: false
  wait: true